### ISSUE TITLE
Support for sub-projects

### ISSUE THREAD

**Issue by michel-kraemer** [stempler/gradle-eclipseconfig#1]
I tested the plugin with Actson (https://github.com/michel-kraemer/actson). It works quite well for the root project, but not for the `examples` sub-project. It only creates the `org.eclipse.jdt.core.prefs` file but not the other files (such as `org.eclipse.jdt.ui.prefs`).

**Comment by stempler** [comment]
Did you apply the plugin also explicitly to your subproject(s)?
If not, then that would be the behavior I would expect.

If you did, then that would involve some more digging. Maybe the `.editorconfig` is not read correctly in that case. If the `org.eclipse.jdt.core.prefs` file is there, does it contain any of the settings that _eclipseconfig_ would set? (like indentation)

**Comment by michel-kraemer** [comment]
You're right. I still had another `eclipse` configuration in my sub-project's build file, so I didn't see that I had forgotten to apply the plugin there as well. Sorry.

**Comment by stempler** [comment]
One thing that should definitely be improved related to subprojects at some point, is that right now the `codetemplates.xml` file would have to be copied to every subproject.

**Comment by michel-kraemer** [comment]
Couldn't you make the location of `codetemplates.xml` configurable? Then people could use

```
codetemplatesFile = new File(rootProject.projectDir, "codetemplates.xml")
```

**Comment by stempler** [comment]
Yes, sure. Just didn't do that yet because when I introduced the feature I didn't have an extension object yet.

**Comment by michel-kraemer** [comment]
So, should we open a new issue or reopen this one?
